version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
init:
  - net start MSSQL$SQL2019
branches:
  only:
  - master
  - develop
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'  
environment:
  MyGetApiKey:
    secure: kDoo1IiHXI3ui641kE3luA3a2uic12F2AeHTOoOzs93zdcIn3A9fsYg3ka31nwnO
  NugetApiKey:
    secure: G5HVnr8m/5cnqGweoUslJ2cY5b+KjZ1t0Cz3WUlIMV8ZiUhaNmWbdfPUFG5kXBWR
nuget:
  account_feed: true
  project_feed: true
before_build:
  - ps: gitversion /l console /output buildserver
build:
  verbosity: detailed
build_script:
  - ps: ./build.ps1
test: off
deploy_script:
  - ps: ./build.ps1 Pack
  - ps: ./build.ps1 Push --NugetApiUrl "https://www.myget.org/F/noctusoft/api/v2/package" --NugetApiKey $env:MyGetApiKey
notifications:
  - provider: Email
    to:
    - rvegajr@noctsuft.com
    subject: Ez Db Code Gen has been successfully deployed
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false