version: 1.4.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - develop
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  MyGetApiKey:
    secure: kDoo1IiHXI3ui641kE3luA3a2uic12F2AeHTOoOzs93zdcIn3A9fsYg3ka31nwnO
  NugetApiKey:
    secure: G5HVnr8m/5cnqGweoUslJ2cY5b+KjZ1t0Cz3WUlIMV8ZiUhaNmWbdfPUFG5kXBWR
cache: packages -> **\packages.config
nuget:
  account_feed: true
  project_feed: true
build_script:
  - ps: gitversion /l console /output buildserver
  - cmd: appveyor-retry dotnet restore .\Src\  --disable-parallel --configfile .\nuget.config.xml --packages .\packages
  - cmd: dotnet build .\Src\ --configuration Release 
test_script:
- cmd: cd .\Src\ && dotnet test -l "console;verbosity=minimal"
deploy_script:
- cmd: dotnet pack ./EzDbCodeGen.Cli/ -o ../artifacts/ --version-suffix "ci-1234" /p:Version=1.4.0
notifications:
- provider: Email
  to:
  - rvegajr@noctsuft.com
  subject: Ez Db Code Gen has been successfully deployed
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false