<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>A powerful .NET library for database-driven code generation. Generate models, repositories, and APIs from your database schema.</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>EzDbCodeGen</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputPath>..\..\bin\$(Configuration)</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Update="EzDbTemplates\**\*.hbs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ezdbcodegen.config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EzDbSchema.Core" Version="8.4.1" />
    <PackageReference Include="EzDbSchema.MsSql" Version="8.4.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>True</Optimize>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>True</Optimize>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

</Project>