<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>8.3.2</Version>
    <AssemblyVersion>8.3.2.0</AssemblyVersion>
    <FileVersion>8.3.2.0</FileVersion>
    <InformationalVersion>8.3.2</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Handlebars.Net" Version="2.1.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\ez-db-schema-core\Src\EzDbSchema.Core\EzDbSchema.Core.csproj" />
    <ProjectReference Include="..\EzDbCodeGen.Core\EzDbCodeGen.Core.csproj" />
  </ItemGroup>

</Project>
